version: '2.3'

services:
  task:
    build: service
    restart: always
    ports:
      - ${PORT}:31337
    pids_limit: 512
    mem_limit: 128M
    privileged: true
    env_file:
      ./.env
    volumes:
      - ./service/nsjail/logs/:/var/log/nsjail/

